/* Playables build adjustments — generated by scripts/build-playable.js.
   No ads exist on this platform, so every rewarded ad becomes a plain bonus
   and interstitials are removed entirely. Outbound links are hidden to honour
   the "no external calls" rule. */
(function () {
  window.__PLAYABLE__ = true;

  // rewarded ads -> instant bonus, no overlay, no network
  AdManager.showRewarded = function (placement, onReward) {
    Sfx.buy();
    onReward();
  };
  // interstitials never run here
  AdManager.onLevelEnd = function (done) { done(); };

  window.addEventListener('DOMContentLoaded', function () {
    // ad wording becomes bonus wording
    var relabel = {
      'res-double': 'Bonus · 2× coins',
      'btn-free-coins': 'Free bonus · +250 coins',
      'crash-revive': 'Revive',
      'btn-daily-2x': 'Claim 2×',
      'btn-welcome-2x': 'Collect 2×',
    };
    Object.keys(relabel).forEach(function (id) {
      var el = document.getElementById(id);
      if (el) { el.textContent = relabel[id]; el.classList.remove('ad-btn'); el.classList.add('primary'); }
    });
    // no outbound links in a playable
    var online = document.getElementById('btn-legal-online');
    if (online) online.style.display = 'none';
  });
})();
